server:
  port: 21
  passive-ports: 11000-12000
  address: localhost
users:
  - name: test
    password: 1234
    # Mounts like docker, but do not support nested mount
    # I mean, mount inside already mounted, please don't
    mounts:
      - "test:/ftp_folder"